name: Build beep_4 APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Dependencies
      run: |
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
        sudo apt-get clean

    - name: Generate buildozer.spec
      run: |
        # Create the buildozer.spec file correctly, ensuring [app] is only once
        cat > buildozer.spec <<EOF
        [app]
        title = beep_4
        package.name = beep4
        package.domain = org.example
        version = 1.0
        # Source directory is the current directory (repository root)
        source.dir = .
        requirements = python3,kivy,requests
        android.permissions = INTERNET, WAKELOCK # Added WAKELOCK as a common Kivy need, adjust as necessary
        android.minsdk = 21 # Recommended minimum for Kivy apps
        android.targetsdk = 33 # Recommended for Google Play submission (adjust if higher is required)
        android.archs = arm64-v8a # Build for modern 64-bit devices

        [buildozer]
        log_level = 2 # Increase for more detailed logs if needed
        # android.enable_aab = True # Consider enabling AAB for Google Play uploads
        EOF
        
        # Optional: Print the spec file to verify it in the logs
        echo "--- buildozer.spec content after generation ---"
        cat buildozer.spec
        echo "----------------------------------------------"

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beep_4-apk
        path: bin/*.apk
        retention-days: 7
