name: Build beep_4 APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Core Dependencies
      run: |
        pip install buildozer
        pip install cython

        sudo apt-get update
        # Install basic build tools and Java needed by Buildozer and Android SDK
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev libffi-dev python3-dev openjdk-17-jdk
        sudo apt-get clean

        # Ensure Git is installed and available, as Buildozer uses it to clone p4a
        echo "Checking Git installation..."
        which git
        git --version
        if [ $? -ne 0 ]; then
            echo "Git is not found or not working. Exiting."
            exit 1
        fi
        echo "Git check complete."

        echo "Cleaning old Android SDK/NDK cache for a fresh start..."
        buildozer android clean

        echo "Updating/downloading Android SDK, NDK, and Python-for-Android components (this can take significant time)..."
        # The --verbose flag should give us more clues if it fails
        # Using 'true' after the command allows the workflow to continue to diagnostic steps even if this fails
        # but we'll add an explicit check to fail later if p4a is still missing.
        buildozer android update --verbose || true
        echo "Android SDK/NDK/P4A update initiated."

        # --- CRITICAL DIAGNOSTIC: Check for python-for-android existence ---
        P4A_TARGET_DIR="/home/runner/work/beep_4/beep_4/.buildozer/android/platform/python-for-android"
        echo "Verifying presence of python-for-android at: $P4A_TARGET_DIR"
        
        if [ -d "$P4A_TARGET_DIR" ]; then
            echo "SUCCESS: python-for-android directory found! Listing its contents for verification:"
            ls -la "$P4A_TARGET_DIR"
            echo "Attempting a quick 'git status' inside p4a (if it's a git repo):"
            git -C "$P4A_TARGET_DIR" status || echo "Could not run git status in p4a directory (might not be a clean git clone)."
        else
            echo "ERROR: python-for-android directory NOT found after 'buildozer android update'!"
            echo "This indicates a failure in cloning or extracting python-for-android."
            echo "Review the 'buildozer android update' output above for errors."
            echo "If the problem persists, consider uncommenting 'p4a.branch = develop' in buildozer.spec as a workaround."
            exit 1 # Fail the job here explicitly if p4a is still missing
        fi
        echo "------------------------------------------"
        # --- END CRITICAL DIAGNOSTIC ---

    - name: Generate buildozer.spec
      run: |
        cat > buildozer.spec <<EOF
        [app]
        title = beep_4
        package.name = beep4
        package.domain = org.example
        version = 1.0
        source.dir = .
        requirements = python3,kivy,requests
        android.permissions = INTERNET, WAKELOCK
        android.minsdk = 21
        android.targetsdk = 33
        android.archs = arm64-v8a

        # If python-for-android continues to fail, uncomment this line:
        # p4a.branch = develop

        [buildozer]
        log_level = 2
        EOF
        
        echo "--- buildozer.spec content after generation ---"
        cat buildozer.spec
        echo "----------------------------------------------"

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beep_4-apk
        path: bin/*.apk
        retention-days: 7
