name: Build beep_4 APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Core Dependencies
      run: |
        pip install buildozer
        pip install cython

        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev libffi-dev python3-dev openjdk-17-jdk git
        sudo apt-get clean

        P4A_DIR="/home/runner/work/beep_4/beep_4/.buildozer/android/platform/python-for-android"
        BUILD_PLATFORM_DIR="/home/runner/work/beep_4/beep_4/.buildozer/android/platform"

        echo "Ensuring necessary Buildozer Android platform directories exist..."
        mkdir -p "$BUILD_PLATFORM_DIR"
        
        # --- Attempt to clone python-for-android manually if it's missing ---
        if [ ! -d "$P4A_DIR" ]; then
            echo "python-for-android not found. Attempting to clone it manually..."
            git clone https://github.com/kivy/python-for-android "$P4A_DIR" || { echo "ERROR: Manual python-for-android clone failed!"; exit 1; }
            echo "Manual python-for-android clone successful."
        else
            echo "python-for-android directory already exists. Skipping manual clone."
        fi
        
        # --- Now run buildozer's clean and update ---
        echo "Cleaning Buildozer Android build artifacts and SDK/NDK cache..."
        # Use || true to prevent this specific clean command from failing the workflow if the .buildozer dir is brand new
        buildozer android clean || true 
        
        echo "Running buildozer android update to ensure SDK, NDK, and p4a configuration..."
        # This will also ensure correct p4a branch/commit based on buildozer.spec
        buildozer android update --verbose || { echo "ERROR: buildozer android update failed!"; exit 1; }
        echo "Buildozer android update complete."

        # --- FINAL CRITICAL DIAGNOSTIC ---
        echo "Final verification: Checking for python-for-android at: $P4A_DIR"
        if [ -d "$P4A_DIR" ]; then
            echo "SUCCESS: python-for-android directory found! Listing its contents:"
            ls -la "$P4A_DIR"
        else
            echo "FATAL ERROR: python-for-android directory is STILL MISSING!"
            exit 1
        fi
        echo "------------------------------------------"

    - name: Generate buildozer.spec
      run: |
        cat > buildozer.spec <<EOF
        [app]
        title = beep_4
        package.name = beep4
        package.domain = org.example
        version = 1.0
        source.dir = .
        requirements = python3,kivy,requests
        android.permissions = INTERNET, WAKELOCK
        android.minsdk = 21
        android.targetsdk = 33
        android.archs = arm64-v8a

        # If issues persist, uncomment this to try a specific branch for p4a
        # p4a.branch = develop

        [buildozer]
        log_level = 2
        EOF
        
        echo "--- buildozer.spec content after generation ---"
        cat buildozer.spec
        echo "----------------------------------------------"

    - name: Build APK
      run: |
        # Use --log-level 5 for very verbose output during the actual build
        buildozer -v android debug --log-level 5
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beep_4-apk
        path: bin/*.apk
        retention-days: 7
