name: Build beep_4 APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Dependencies
      run: |
        pip install buildozer
        pip install cython

        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk # Ensure Java for Android SDK
        sudo apt-get clean

        echo "Cleaning old Android SDK/NDK cache..."
        buildozer android clean
        
        echo "Updating/downloading Android SDK, NDK, and Python-for-Android components..."
        # Force a complete update of SDK/NDK/p4a.
        # This command is critical for ensuring python-for-android is cloned.
        # It can take a long time and might seem stuck, be patient.
        buildozer android update --verbose # Add --verbose for more detailed output here
        echo "Android SDK/NDK/P4A update complete."

        # --- DIAGNOSTIC STEP for python-for-android ---
        P4A_DIR="/home/runner/work/beep_4/beep_4/.buildozer/android/platform/python-for-android"
        echo "Checking for python-for-android directory: $P4A_DIR"
        if [ -d "$P4A_DIR" ]; then
            echo "python-for-android directory found! Listing contents:"
            ls -la "$P4A_DIR"
        else
            echo "ERROR: python-for-android directory NOT found!"
            exit 1 # Fail the job explicitly if p4a is missing here
        fi
        echo "------------------------------------------"
        # --- END DIAGNOSTIC STEP ---

    - name: Generate buildozer.spec
      run: |
        cat > buildozer.spec <<EOF
        [app]
        title = beep_4
        package.name = beep4
        package.domain = org.example
        version = 1.0
        source.dir = .
        requirements = python3,kivy,requests
        android.permissions = INTERNET, WAKELOCK
        android.minsdk = 21
        android.targetsdk = 33
        android.archs = arm64-v8a

        # Optional: Specify the python-for-android branch
        # This can sometimes resolve issues with newer Python versions or specific buildozer/p4a compatibility.
        # Uncomment the line below if the error persists.
        # p4a.branch = develop

        [buildozer]
        log_level = 2
        EOF
        
        echo "--- buildozer.spec content after generation ---"
        cat buildozer.spec
        echo "----------------------------------------------"

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beep_4-apk
        path: bin/*.apk
        retention-days: 7
