name: Build beep_4 APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Dependencies
      run: |
        pip install buildozer
        pip install cython # Keep this, it fixed the previous issue.

        # Ensure apt packages are up-to-date and necessary Java is installed
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
        sudo apt-get clean

        # IMPORTANT: Clean previous Android SDK/NDK cache and then update/install them
        # This helps ensure all components, including build-tools (which contains aidl), are fresh.
        echo "Cleaning old Android SDK/NDK cache..."
        buildozer android clean
        echo "Updating/downloading Android SDK and NDK components (this may take a while)..."
         
        # You can add 'yes |' before buildozer android update if it ever asks for license acceptance,
        # but Buildozer usually handles this automatically in CI.
        yes | buildozer android update
        echo "Android SDK/NDK update complete."

    - name: Generate buildozer.spec
      run: |
        cat > buildozer.spec <<EOF
        [app]
        title = beep_4
        package.name = beep4
        package.domain = org.example
        version = 1.0
        source.dir = .
        requirements = python3,kivy,requests
        android.permissions = INTERNET, WAKELOCK
        android.minsdk = 21
        android.targetsdk = 33
        android.archs = arm64-v8a

        [buildozer]
        log_level = 2
        EOF
        
        echo "--- buildozer.spec content after generation ---"
        cat buildozer.spec
        echo "----------------------------------------------"

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beep_4-apk
        path: bin/*.apk
        retention-days: 7
